package com.plugtree.solradvert;

/**
 *      Copyright 2011 Plugtree LLC
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

import com.plugtree.solradvert.core.*;
import com.plugtree.solradvert.fact.*;
import com.plugtree.solradvert.testmodel.*;

import org.apache.lucene.search.*;

import org.apache.solr.handler.component.*;

rule "When a brand appears in a query, move it to a filter"
  when
    $aq : AdvertQuery()
    $rb : ResponseBuilder()
    
    $child : TermQuery($txt : term.text)
    $brand : Brand(name==$txt)
    $rel : ParentChildRelationship(child==$child)
    inMainQuery($child;) 
  then
    $aq.addFilter("brand:" + $txt);
    $rel.remove();
end
