package com.plugtree.solradvert;

/**
 *      Copyright 2011 Plugtree LLC
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
import com.plugtree.solradvert.core.*;

rule "Boost Adidas products when searching shoes"
  when
    Query has term "shoes" in field "product"
    Or
    Query has term "aodsifjao" in field "product"
  then
    Add boost query "{!lucene}brand:adidas"
end

rule "Sort products by price when searching tennis racquets"
  when
    Query has term "tennis racquet" in field "product"
  then
    Set sort "price asc"
end
