package com.plugtree.solradvert;

/**
 *      Copyright 2011 Plugtree LLC
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

import com.plugtree.solradvert.core.*;

rule "Boost Adidas products when searching shoes"
	when
		$aq : AdvertQuery(eval($aq.hasTerm("product", "shoes")))
	then
		$aq.boost("{!lucene}brand:adidas");
end

rule "Sort products by price when searching tennis racquets"
	when
		$aq : AdvertQuery(eval($aq.hasTerm("product", "tennis racquet")))
	then
		$aq.setSort("price asc");
end
